/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as appRouteRouteImport } from './routes/(app)/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoTableRouteImport } from './routes/demo/table'
import { Route as publicLoginRouteImport } from './routes/(public)/login'
import { Route as appSettingsRouteImport } from './routes/(app)/settings'
import { Route as appDashboardRouteImport } from './routes/(app)/dashboard'
import { Route as appSettingsIndexRouteImport } from './routes/(app)/settings.index'
import { Route as appSettingsUsersRouteImport } from './routes/(app)/settings.users'
import { Route as appSettingsInvitesRouteImport } from './routes/(app)/settings.invites'
import { Route as publicInvitesInviteIdConfirmRouteImport } from './routes/(public)/invites.$inviteId.confirm'

const appRouteRoute = appRouteRouteImport.update({
  id: '/(app)',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTableRoute = DemoTableRouteImport.update({
  id: '/demo/table',
  path: '/demo/table',
  getParentRoute: () => rootRouteImport,
} as any)
const publicLoginRoute = publicLoginRouteImport.update({
  id: '/(public)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const appSettingsRoute = appSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => appRouteRoute,
} as any)
const appDashboardRoute = appDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => appRouteRoute,
} as any)
const appSettingsIndexRoute = appSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => appSettingsRoute,
} as any)
const appSettingsUsersRoute = appSettingsUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => appSettingsRoute,
} as any)
const appSettingsInvitesRoute = appSettingsInvitesRouteImport.update({
  id: '/invites',
  path: '/invites',
  getParentRoute: () => appSettingsRoute,
} as any)
const publicInvitesInviteIdConfirmRoute =
  publicInvitesInviteIdConfirmRouteImport.update({
    id: '/(public)/invites/$inviteId/confirm',
    path: '/invites/$inviteId/confirm',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardRoute
  '/settings': typeof appSettingsRouteWithChildren
  '/login': typeof publicLoginRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/settings/invites': typeof appSettingsInvitesRoute
  '/settings/users': typeof appSettingsUsersRoute
  '/settings/': typeof appSettingsIndexRoute
  '/invites/$inviteId/confirm': typeof publicInvitesInviteIdConfirmRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard': typeof appDashboardRoute
  '/login': typeof publicLoginRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/settings/invites': typeof appSettingsInvitesRoute
  '/settings/users': typeof appSettingsUsersRoute
  '/settings': typeof appSettingsIndexRoute
  '/invites/$inviteId/confirm': typeof publicInvitesInviteIdConfirmRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/(app)': typeof appRouteRouteWithChildren
  '/(app)/dashboard': typeof appDashboardRoute
  '/(app)/settings': typeof appSettingsRouteWithChildren
  '/(public)/login': typeof publicLoginRoute
  '/demo/table': typeof DemoTableRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/(app)/settings/invites': typeof appSettingsInvitesRoute
  '/(app)/settings/users': typeof appSettingsUsersRoute
  '/(app)/settings/': typeof appSettingsIndexRoute
  '/(public)/invites/$inviteId/confirm': typeof publicInvitesInviteIdConfirmRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard'
    | '/settings'
    | '/login'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/settings/invites'
    | '/settings/users'
    | '/settings/'
    | '/invites/$inviteId/confirm'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard'
    | '/login'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/settings/invites'
    | '/settings/users'
    | '/settings'
    | '/invites/$inviteId/confirm'
  id:
    | '__root__'
    | '/'
    | '/(app)'
    | '/(app)/dashboard'
    | '/(app)/settings'
    | '/(public)/login'
    | '/demo/table'
    | '/demo/tanstack-query'
    | '/(app)/settings/invites'
    | '/(app)/settings/users'
    | '/(app)/settings/'
    | '/(public)/invites/$inviteId/confirm'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  appRouteRoute: typeof appRouteRouteWithChildren
  publicLoginRoute: typeof publicLoginRoute
  DemoTableRoute: typeof DemoTableRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  publicInvitesInviteIdConfirmRoute: typeof publicInvitesInviteIdConfirmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(app)': {
      id: '/(app)'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof appRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/table': {
      id: '/demo/table'
      path: '/demo/table'
      fullPath: '/demo/table'
      preLoaderRoute: typeof DemoTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(public)/login': {
      id: '/(public)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof publicLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/(app)/settings': {
      id: '/(app)/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof appSettingsRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/dashboard': {
      id: '/(app)/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof appDashboardRouteImport
      parentRoute: typeof appRouteRoute
    }
    '/(app)/settings/': {
      id: '/(app)/settings/'
      path: '/'
      fullPath: '/settings/'
      preLoaderRoute: typeof appSettingsIndexRouteImport
      parentRoute: typeof appSettingsRoute
    }
    '/(app)/settings/users': {
      id: '/(app)/settings/users'
      path: '/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof appSettingsUsersRouteImport
      parentRoute: typeof appSettingsRoute
    }
    '/(app)/settings/invites': {
      id: '/(app)/settings/invites'
      path: '/invites'
      fullPath: '/settings/invites'
      preLoaderRoute: typeof appSettingsInvitesRouteImport
      parentRoute: typeof appSettingsRoute
    }
    '/(public)/invites/$inviteId/confirm': {
      id: '/(public)/invites/$inviteId/confirm'
      path: '/invites/$inviteId/confirm'
      fullPath: '/invites/$inviteId/confirm'
      preLoaderRoute: typeof publicInvitesInviteIdConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface appSettingsRouteChildren {
  appSettingsInvitesRoute: typeof appSettingsInvitesRoute
  appSettingsUsersRoute: typeof appSettingsUsersRoute
  appSettingsIndexRoute: typeof appSettingsIndexRoute
}

const appSettingsRouteChildren: appSettingsRouteChildren = {
  appSettingsInvitesRoute: appSettingsInvitesRoute,
  appSettingsUsersRoute: appSettingsUsersRoute,
  appSettingsIndexRoute: appSettingsIndexRoute,
}

const appSettingsRouteWithChildren = appSettingsRoute._addFileChildren(
  appSettingsRouteChildren,
)

interface appRouteRouteChildren {
  appDashboardRoute: typeof appDashboardRoute
  appSettingsRoute: typeof appSettingsRouteWithChildren
}

const appRouteRouteChildren: appRouteRouteChildren = {
  appDashboardRoute: appDashboardRoute,
  appSettingsRoute: appSettingsRouteWithChildren,
}

const appRouteRouteWithChildren = appRouteRoute._addFileChildren(
  appRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  appRouteRoute: appRouteRouteWithChildren,
  publicLoginRoute: publicLoginRoute,
  DemoTableRoute: DemoTableRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  publicInvitesInviteIdConfirmRoute: publicInvitesInviteIdConfirmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
