// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type HealthGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/health_checks_controller.ts').default['handle'], false>
}
type ApiSessionPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/validators/session.ts')['sessionStoreValidator']>>
  response: MakeTuyauResponse<import('../app/controllers/session_controller.ts').default['store'], true>
}
type ApiSessionDelete = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/session_controller.ts').default['destroy'], false>
}
type ApiSessionGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/controllers/session_controller.ts').default['me'], false>
}
export interface ApiDefinition {
  'health': {
    '$url': {
    };
    '$get': HealthGetHead;
    '$head': HealthGetHead;
  };
  'api': {
    'session': {
      '$url': {
      };
      '$post': ApiSessionPost;
      '$delete': ApiSessionDelete;
      '$get': ApiSessionGetHead;
      '$head': ApiSessionGetHead;
    };
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
